on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  check-news-file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pipx run towncrier check --compare-with origin/main
        if: ${{ ! contains(github.event.issue.labels.*.name, 'trivial') }}
